### ISSUE TITLE
Project folder organization

### ISSUE THREAD

**Issue by ghost** [sarika-arora/prj-rev-bwfs-tea-cozy#1]
https://github.com/sarika-arora/prj-rev-bwfs-tea-cozy/tree/master/tea-cozy/resources

Very nice job including the images in their own `images` folder and your stylesheets in their own `css` folder. This is very organized and easy to navigate 👍 

https://github.com/sarika-arora/prj-rev-bwfs-tea-cozy/blob/master/tea-cozy/index.html#L11

Likewise, good job using relative file paths to these assets in your project!

**Comment by sarika-arora** [comment]
Thanks a lot!
