### ISSUE TITLE
Image alt attributes

### ISSUE THREAD

**Issue by ghost** [sarika-arora/prj-rev-bwfs-tea-cozy#2]
https://github.com/sarika-arora/prj-rev-bwfs-tea-cozy/blob/master/tea-cozy/index.html#L11

The `alt` attribute should not be an error message. It should be a message describing what the image is, so that someone accessing your website can still find it useful even without the images.

This is of particular importance for visually impaired users who frequently use e-readers and devices that neglect images altogether. They depend on these descriptions of your page's content in order to use it.

**Comment by sarika-arora** [comment]
Good to know! I'll definitely use a better message describing my image next time. Thanks!
