### ISSUE TITLE
Semantic markup

### ISSUE THREAD

**Issue by ghost** [sarika-arora/prj-rev-bwfs-tea-cozy#3]
https://github.com/sarika-arora/prj-rev-bwfs-tea-cozy/blob/master/tea-cozy/index.html#L9-L23

Nice job using some semantic tags here, like `header`, `nav`, and `footer`.

Aim to make your code as semantic as possible. Some other tags you might consider are: `menu`, `main`, `figure`, `figcaption`, `section`, and others. Making use of these HTML5 semantic tags will make your code easier to reason about and reduce the classes and IDs you need to give to the elements on your page.

**Comment by sarika-arora** [comment]
Got it! I am already reading about it! Thanks again!
