### ISSUE TITLE
Class names

### ISSUE THREAD

**Issue by ghost** [sarika-arora/prj-rev-bwfs-tea-cozy#4]
https://github.com/sarika-arora/prj-rev-bwfs-tea-cozy/blob/master/tea-cozy/index.html#L39-L59

Try to use something more descriptive than `list-item` for a class name, otherwise you're forcing another programmer (or your future self) to read through all the content to understand what your page is about.

A class like `tea` would be very useful to have in a list of teas.

**Comment by sarika-arora** [comment]
I totally get what you are saying. I think I got caught into details like not every item was a tea and so ended up using a generic name, but I will definitely keep this in mind next time I am assigning class names. Appreciate the feedback!
