### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by ghost** [sarika-arora/prj-rev-bwfs-tea-cozy#5]
Satisfactory 👍 

Nice job getting the website looking like the design, you've definitely got a good handle on the material covered so far having efficiently used both basic CSS properties and more sophisticated methods like `flexbox`.

See if you can improve the quality of your code by adhering to modern accessibility standards like `alt` attributes and also semantic markup. You should also try to think of more strategic class names so that it's easier to reason about your code.

Make sure you come back to this project later on when you've covered media queries and try to make it mobile responsive! There's no reason why you shouldn't make this into a more viable portfolio piece!

**Comment by sarika-arora** [comment]
Thanks Steve! I appreciate the feedback!
